import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'en' | 'hi' | 'es' | 'fr' | 'ta'

interface Translations {
    [key: string]: string
}

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
}

const translations: Record<Language, Translations> = {
    en: {
        'settings': 'Settings',
        'languagePreferences': 'Language Preferences',
        'selectLanguage': 'Select Language',
        'notifications': 'Notifications',
        'enableNotifications': 'Enable Notifications',
        'enableNotificationsDesc': 'Receive health alerts and updates',
        'notificationTypes': 'Notification Types',
        'incidentNotifications': 'Incident Notifications',
        'zoneAlerts': 'Zone Entry Alerts',
        'emergencyNotifications': 'Emergency Notifications',
        'sosAlerts': 'SOS Alerts',
        'locationPrivacy': 'Location & Privacy',
        'locationServices': 'Location Services',
        'locationServicesDesc': 'Allow location access for risk mapping',
        'locationAccuracy': 'Location Accuracy',
        'locationNetwork': 'Location + Network',
        'locationOnly': 'Location',
        'networkOnly': 'Network',
        'appearance': 'Appearance',
        'darkTheme': 'Dark Theme',
        'darkThemeDesc': 'Use dark color scheme',
        'dataPrivacy': 'Data & Privacy',
        'exportData': 'Export My Data',
        'deleteAccount': 'Delete Account',
        'home': 'Home',
        'map': 'Map',
        'sos': 'SOS',
        'tips': 'Tips',
        'profile': 'Profile',
        'aiSafetyScore': 'AI Safety Score',
        'lowRisk': 'Low Risk',
        'mediumRisk': 'Medium Risk',
        'highRisk': 'High Risk',
        'lastUpdated': 'Last updated: Just now',
        'quickActions': 'Quick Actions',
        'emergencyPanic': 'Emergency Panic',
        'reportIncident': 'Report Incident',
        'nearbyIncidents': 'Nearby Incidents',
        'aiSafetyDetection': 'AI Safety Detection',
        'smartChatbot': 'Smart Chatbot',
        'profileManager': 'Profile Manager',
        'communityInteraction': 'Community Interaction',
        'nearbyPlaces': 'Nearby Places',
        'liveStatistics': 'Live Statistics',
        'nearbyTourists': 'Nearby Tourists',
        'activeAlerts': 'Active Alerts',
        'emergencyResponse': 'Emergency Response',
        'aiConfidence': 'AI Confidence',
        'currentLocationStatus': 'Current Location Status',
        'emergencyModeActive': 'Emergency Mode Active',
        'sendEmergencyAlert': 'Send Emergency Alert',
        'emergencyType': 'Emergency Type',
        'descriptionOptional': 'Description (Optional)',
        'cancel': 'Cancel',
    },
    hi: {
        'settings': 'सेटिंग्स',
        'languagePreferences': 'भाषा प्राथमिकताएं',
        'selectLanguage': 'भाषा चुनें',
        'notifications': 'सूचनाएं',
        'enableNotifications': 'सूचनाएं सक्षम करें',
        'enableNotificationsDesc': 'स्वास्थ्य अलर्ट और अपडेट प्राप्त करें',
        'notificationTypes': 'सूचना प्रकार',
        'incidentNotifications': 'घटना सूचनाएं',
        'zoneAlerts': 'ज़ोन प्रवेश अलर्ट',
        'emergencyNotifications': 'आपातकालीन सूचनाएं',
        'sosAlerts': 'एसओएस अलर्ट',
        'locationPrivacy': 'स्थान और गोपनीयता',
        'locationServices': 'स्थान सेवाएं',
        'locationServicesDesc': 'जोखिम मानचित्रण के लिए स्थान पहुंच की अनुमति दें',
        'locationAccuracy': 'स्थान सटीकता',
        'locationNetwork': 'स्थान + नेटवर्क',
        'locationOnly': 'स्थान',
        'networkOnly': 'नेटवर्क',
        'appearance': 'रूप',
        'darkTheme': 'डार्क थीम',
        'darkThemeDesc': 'डार्क रंग स्कीम का उपयोग करें',
        'dataPrivacy': 'डेटा और गोपनीयता',
        'exportData': 'मेरा डेटा निर्यात करें',
        'deleteAccount': 'खाता हटाएं',
        'home': 'होम',
        'map': 'मानचित्र',
        'sos': 'एसओएस',
        'tips': 'सुझाव',
        'profile': 'प्रोफ़ाइल',
        'aiSafetyScore': 'AI सुरक्षा स्कोर',
        'lowRisk': 'कम जोखिम',
        'mediumRisk': 'मध्यम जोखिम',
        'highRisk': 'उच्च जोखिम',
        'lastUpdated': 'अंतिम अपडेट: अभी',
        'quickActions': 'त्वरित कार्रवाई',
        'emergencyPanic': 'आपातकालीन',
        'reportIncident': 'घटना रिपोर्ट',
        'nearbyIncidents': 'पास की घटनाएं',
        'aiSafetyDetection': 'AI सुरक्षा पहचान',
        'smartChatbot': 'स्मार्ट चैटबॉट',
        'profileManager': 'प्रोफ़ाइल प्रबंधक',
        'communityInteraction': 'सामुदायिक बातचीत',
        'nearbyPlaces': 'नज़दीकी स्थान',
        'liveStatistics': 'लाइव आँकड़े',
        'nearbyTourists': 'पास के पर्यटक',
        'activeAlerts': 'सक्रिय अलर्ट',
        'emergencyResponse': 'आपातकालीन प्रतिक्रिया',
        'aiConfidence': 'AI विश्वास',
        'currentLocationStatus': 'वर्तमान स्थान स्थिति',
        'emergencyModeActive': 'आपातकालीन मोड सक्रिय',
        'sendEmergencyAlert': 'आपातकालीन अलर्ट भेजें',
        'emergencyType': 'आपातकालीन प्रकार',
        'descriptionOptional': 'विवरण (वैकल्पिक)',
        'cancel': 'रद्द करें',
    },
    ta: {
        'settings': 'அமைப்புகள்',
        'languagePreferences': 'மொழி விருப்பங்கள்',
        'selectLanguage': 'மொழியைத் தேர்ந்தெடுக்கவும்',
        'notifications': 'அறிவிப்புகள்',
        'enableNotifications': 'அறிவிப்புகளை இயக்கு',
        'enableNotificationsDesc': 'சுகாதார எச்சரிக்கைகள் மற்றும் புதுப்பிப்புகளைப் பெறுங்கள்',
        'notificationTypes': 'அறிவிப்பு வகைகள்',
        'incidentNotifications': 'சம்பவ அறிவிப்புகள்',
        'zoneAlerts': 'மண்டல நுழைவு எச்சரிக்கைகள்',
        'emergencyNotifications': 'அவசர அறிவிப்புகள்',
        'sosAlerts': 'எஸ்ஓஎஸ் எச்சரிக்கைகள்',
        'locationPrivacy': 'இருப்பிடம் & தனியுரிமை',
        'locationServices': 'இருப்பிட சேவைகள்',
        'locationServicesDesc': 'ஆபத்து வரைபடத்திற்கு இருப்பிட அணுகலை அனுமதிக்கவும்',
        'locationAccuracy': 'இருப்பிட துல்லியம்',
        'locationNetwork': 'இருப்பிடம் + நெட்வொர்க்',
        'locationOnly': 'இருப்பிடம்',
        'networkOnly': 'நெட்வொர்க்',
        'appearance': 'தோற்றம்',
        'darkTheme': 'டார்க் தீம்',
        'darkThemeDesc': 'இருண்ட நிற திட்டத்தைப் பயன்படுத்தவும்',
        'dataPrivacy': 'தரவு & தனியுரிமை',
        'exportData': 'எனது தரவை ஏற்றுமதி செய்',
        'deleteAccount': 'கணக்கை நீக்கு',
        'home': 'முகப்பு',
        'map': 'வரைபடம்',
        'sos': 'எஸ்ஓஎஸ்',
        'tips': 'குறிப்புகள்',
        'profile': 'சுயவிவரம்',
        'aiSafetyScore': 'AI பாதுகாப்பு மதிப்பெண்',
        'lowRisk': 'குறைந்த ஆபத்து',
        'mediumRisk': 'நடுத்தர ஆபத்து',
        'highRisk': 'அதிக ஆபத்து',
        'lastUpdated': 'கடைசி புதுப்பிப்பு: இப்போது',
        'quickActions': 'விரைவு செயல்கள்',
        'emergencyPanic': 'அவசர பீதி',
        'reportIncident': 'சம்பவ அறிக்கை',
        'nearbyIncidents': 'அருகிலுள்ள சம்பவங்கள்',
        'aiSafetyDetection': 'AI பாதுகாப்பு கண்டறிதல்',
        'smartChatbot': 'ஸ்மார்ட் சாட்பாட்',
        'profileManager': 'சுயவிவர மேலாளர்',
        'communityInteraction': 'சமூக தொடர்பு',
        'nearbyPlaces': 'அருகிலுள்ள இடங்கள்',
        'liveStatistics': 'நேரடி புள்ளிவிவரங்கள்',
        'nearbyTourists': 'அருகிலுள்ள சுற்றுலா',
        'activeAlerts': 'செயலில் எச்சரிக்கைகள்',
        'emergencyResponse': 'அவசர பதில்',
        'aiConfidence': 'AI நம்பிக்கை',
        'currentLocationStatus': 'தற்போதைய இருப்பிட நிலை',
        'emergencyModeActive': 'அவசர பயன்முறை செயலில்',
        'sendEmergencyAlert': 'அவசர எச்சரிக்கை அனுப்பு',
        'emergencyType': 'அவசர வகை',
        'descriptionOptional': 'விவரம் (விருப்பம்)',
        'cancel': 'ரத்து செய்',
    },
    es: {
        'settings': 'Configuración',
        'languagePreferences': 'Preferencias de Idioma',
        'selectLanguage': 'Seleccionar Idioma',
        'notifications': 'Notificaciones',
        'enableNotifications': 'Activar Notificaciones',
        'enableNotificationsDesc': 'Recibir alertas y actualizaciones de salud',
        'notificationTypes': 'Tipos de Notificación',
        'incidentNotifications': 'Notificaciones de Incidentes',
        'zoneAlerts': 'Alertas de Zona',
        'emergencyNotifications': 'Notificaciones de Emergencia',
        'sosAlerts': 'Alertas SOS',
        'locationPrivacy': 'Ubicación y Privacidad',
        'locationServices': 'Servicios de Ubicación',
        'locationServicesDesc': 'Permitir acceso a ubicación para mapeo de riesgos',
        'locationAccuracy': 'Precisión de Ubicación',
        'locationNetwork': 'Ubicación + Red',
        'locationOnly': 'Ubicación',
        'networkOnly': 'Red',
        'appearance': 'Apariencia',
        'darkTheme': 'Tema Oscuro',
        'darkThemeDesc': 'Usar esquema de colores oscuros',
        'dataPrivacy': 'Datos y Privacidad',
        'exportData': 'Exportar Mis Datos',
        'deleteAccount': 'Eliminar Cuenta',
        'home': 'Inicio',
        'map': 'Mapa',
        'sos': 'SOS',
        'tips': 'Consejos',
        'profile': 'Perfil',
        'aiSafetyScore': 'Puntuación de Seguridad AI',
        'lowRisk': 'Riesgo Bajo',
        'mediumRisk': 'Riesgo Medio',
        'highRisk': 'Riesgo Alto',
        'lastUpdated': 'Última actualización: Ahora',
        'quickActions': 'Acciones Rápidas',
        'emergencyPanic': 'Pánico de Emergencia',
        'reportIncident': 'Reportar Incidente',
        'nearbyIncidents': 'Incidentes Cercanos',
        'aiSafetyDetection': 'Detección de Seguridad AI',
        'smartChatbot': 'Chatbot Inteligente',
        'profileManager': 'Gestor de Perfil',
        'communityInteraction': 'Interacción Comunitaria',
        'nearbyPlaces': 'Lugares Cercanos',
        'liveStatistics': 'Estadísticas en Vivo',
        'nearbyTourists': 'Turistas Cercanos',
        'activeAlerts': 'Alertas Activas',
        'emergencyResponse': 'Respuesta de Emergencia',
        'aiConfidence': 'Confianza AI',
        'currentLocationStatus': 'Estado de Ubicación Actual',
        'emergencyModeActive': 'Modo de Emergencia Activo',
        'sendEmergencyAlert': 'Enviar Alerta de Emergencia',
        'emergencyType': 'Tipo de Emergencia',
        'descriptionOptional': 'Descripción (Opcional)',
        'cancel': 'Cancelar',
    },
    fr: {
        'settings': 'Paramètres',
        'languagePreferences': 'Préférences de Langue',
        'selectLanguage': 'Sélectionner la Langue',
        'notifications': 'Notifications',
        'enableNotifications': 'Activer les Notifications',
        'enableNotificationsDesc': 'Recevoir des alertes et mises à jour de santé',
        'notificationTypes': 'Types de Notifications',
        'incidentNotifications': 'Notifications d\'Incidents',
        'zoneAlerts': 'Alertes de Zone',
        'emergencyNotifications': 'Notifications d\'Urgence',
        'sosAlerts': 'Alertes SOS',
        'locationPrivacy': 'Localisation et Confidentialité',
        'locationServices': 'Services de Localisation',
        'locationServicesDesc': 'Autoriser l\'accès à la localisation pour la cartographie des risques',
        'locationAccuracy': 'Précision de Localisation',
        'locationNetwork': 'Localisation + Réseau',
        'locationOnly': 'Localisation',
        'networkOnly': 'Réseau',
        'appearance': 'Apparence',
        'darkTheme': 'Thème Sombre',
        'darkThemeDesc': 'Utiliser le schéma de couleurs sombres',
        'dataPrivacy': 'Données et Confidentialité',
        'exportData': 'Exporter Mes Données',
        'deleteAccount': 'Supprimer le Compte',
        'home': 'Accueil',
        'map': 'Carte',
        'sos': 'SOS',
        'tips': 'Conseils',
        'profile': 'Profil',
        'aiSafetyScore': 'Score de Sécurité IA',
        'lowRisk': 'Risque Faible',
        'mediumRisk': 'Risque Moyen',
        'highRisk': 'Risque Élevé',
        'lastUpdated': 'Dernière mise à jour: Maintenant',
        'quickActions': 'Actions Rapides',
        'emergencyPanic': 'Panique d\'Urgence',
        'reportIncident': 'Signaler un Incident',
        'nearbyIncidents': 'Incidents à Proximité',
        'aiSafetyDetection': 'Détection de Sécurité IA',
        'smartChatbot': 'Chatbot Intelligent',
        'profileManager': 'Gestionnaire de Profil',
        'communityInteraction': 'Interaction Communautaire',
        'nearbyPlaces': 'Lieux Proches',
        'liveStatistics': 'Statistiques en Direct',
        'nearbyTourists': 'Touristes Proches',
        'activeAlerts': 'Alertes Actives',
        'emergencyResponse': 'Réponse d\'Urgence',
        'aiConfidence': 'Confiance IA',
        'currentLocationStatus': 'État de Localisation Actuel',
        'emergencyModeActive': 'Mode d\'Urgence Actif',
        'sendEmergencyAlert': 'Envoyer une Alerte d\'Urgence',
        'emergencyType': 'Type d\'Urgence',
        'descriptionOptional': 'Description (Optionnel)',
        'cancel': 'Annuler',
    },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('app-language')
        return (saved as Language) || 'en'
    })

    const setLanguage = (lang: Language) => {
        setLanguageState(lang)
        localStorage.setItem('app-language', lang)
    }

    const t = (key: string): string => {
        return translations[language]?.[key] || translations['en']?.[key] || key
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider')
    }
    return context
}
